const lessonData = {
  "Math": {
    1: { p: "1s and 2s", a: "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15; 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30" },
    2: { p: "3s and 4s", a: "3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45; 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60" },
    3: { p: "5s and 6s", a: "5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75; 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90" },
    4: { p: "7s and 8s", a: "7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105; 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120" },
    5: { p: "9s and 10s", a: "9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108, 117, 126, 135; 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150" },
    6: { p: "11s and 12s", a: "11, 22, 33, 44, 55, 66, 77, 88, 99, 110, 121, 132, 143, 154, 165; 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180" },
    7: { p: "13s", a: "13, 26, 39, 52, 65, 78, 91, 104, 117, 130, 143, 156, 169, 182, 195" },
    8: { p: "14s", a: "14, 28, 42, 56, 70, 84, 98, 112, 126, 140, 154, 168, 182, 196, 210" },
    9: { p: "15s", a: "15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225" },
    10: { p: "Squares", a: "1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225" },
    11: { p: "Cubes", a: "1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375" },
    12: { p: "Teaspoons and Tablespoons", a: "3 teaspoons equals 1 tablespoon; 2 tablespoons equals 1 fluid ounce" },
    13: { p: "Liquid Equivalents", a: "8 fluid ounces = 1 cup; 2 cups = 1 pint; 2 pints = 1 quart; 4 quarts = 1 gallon" },
    14: { p: "Linear Equivalents", a: "2.54 centimeters = 1 inch; 12 inches = 1 foot; 5,280 feet = 1 mile" },
    15: { p: "Metric Measurements", a: "10 millimeters = 1 centimeter; 100 centimeters = 1 meter; 1,000 meters = 1 kilometer" },
    16: { p: "Area of a Rectangle", a: "The area of a rectangle equals length times width" },
    17: { p: "Area of a Square", a: "The area of a square equals length of its side squared" },
    18: { p: "Area of a Triangle", a: "The area of a triangle equals one-half base times height" },
    19: { p: "Area of a Circle", a: "The area of a circle equals pi (3.14) times the radius squared" },
    20: { p: "Circumference of a Circle", a: "The circumference of a circle equals 2 times pi (3.14) times the radius" },
    21: { p: "The Associative Law", a: "Addition: (a+b)+c = a+(b+c); Multiplication: (a*b)*c = a*(b*c)" },
    22: { p: "The Commutative Law", a: "Addition: a+b = b+a; Multiplication: a*b = b*a" },
    23: { p: "The Distributive Law", a: "a(b+c) = ab + ac" },
    24: { p: "The Identity Law", a: "Addition: a+0 = a; Multiplication: a*1 = a" }
  },

 "Latin": {
    1: { p: "Prepositions", a: "in (in), apud (with), per (by), sine (without), a (from), de (of)" },
    2: { p: "Conjunctions and Adverbs", a: "et (and), ut (that), non (not)" },
    3: { p: "Pronouns", a: "hic (this), hoc (same), ipso/ipsum (him), cui (whose), quod (that), eam (it), illum (him)" },
    4: { p: "Verbs", a: "erat (was), venit (came), perhiberet (bear), crederent (believe)" },
    5: { p: "Verbs", a: "facta sunt (were made), factum est (was made), missus (sent), comprehenderunt (comprehended), lucet (shineth), fuit (there was)" },
    6: { p: "Nouns", a: "verbum (word), Deus/Deum/Deo (God), principio (beginning), omnia/omnes (all), nihil (nothing)" },
    7: { p: "Nouns", a: "vita (life), lux (light), homo/hominum (man), nomen (name)" },
    8: { p: "Nouns", a: "testimonium (witness, testimony), lumine (light), Iohannes (John), tenebris/tenebrae (darkness)" },
    9: { p: "Verb Rules", a: "Latin verbs have different endings called conjugations." },
    10: { p: "Article Rules", a: "Latin has no translation for articles a, an, the." },
    11: { p: "Nouns/Pronouns Rules", a: "Latin nouns and pronouns have different endings called declensions." },
    12: { p: "John 1:1", a: "In principio erat Verbum (In the beginning was the Word)" },
    13: { p: "John 1:1", a: "et Verbum erat apud Deum et Deus erat Verbum (and the Word was with God and the Word was God)" },
    14: { p: "John 1:2", a: "hoc erat in principio apud Deum (the same was in the beginning with God)" },
    15: { p: "John 1:3", a: "omnia per ipsum facta sunt (all things were made by him)" },
    16: { p: "John 1:3", a: "et sine ipso factum est nihil quod factum est (and without him was made nothing that was made)" },
    17: { p: "John 1:4", a: "in ipso vita erat et vita erat lux hominum (in him was life and the life was the light of men)" },
    18: { p: "John 1:5", a: "et lux in tenebris lucet (and the light shineth in the darkness)" },
    19: { p: "John 1:5", a: "et tenebrae eam non conprehenderunt (and the darkness did not comprehend it)" },
    20: { p: "John 1:6", a: "fuit homo missus a Deo (there was a man sent from God)" },
    21: { p: "John 1:6", a: "cui nomen erat Iohannes (whose name was John)" },
    22: { p: "John 1:7", a: "hic venit in testimonium (this man came for a witness)" },
    23: { p: "John 1:7", a: "ut testimonium perhiberet de lumine (to give testimony of the light)" },
    24: { p: "John 1:7", a: "ut omnes crederent per illum (that all men might believe through him)" }
  },

  "Science": {
    1: { p: "What are four types of tissue?", a: "connective, epithelial, muscle, nerve" },
    2: { p: "Which bones make up the axial skeleton?", a: "skull, vertebrae, ribs, sternum" },
    3: { p: "What are three kinds of muscle?", a: "skeletal, smooth, cardiac" },
    4: { p: "What are three parts of the nervous system?", a: "brain, spinal cord, nerves" },
    5: { p: "What are the five main senses?", a: "sight, hearing, taste, smell, touch" },
    6: { p: "What are some parts of the digestive system?", a: "mouth, esophagus, stomach, liver, small intestine, large intestine" },
    7: { p: "What are four parts of the excretory system?", a: "urinary tract, lungs, skin, intestines" },
    8: { p: "What are six parts of the circulatory system?", a: "heart, arteries, veins, capillaries, red and white blood cells, platelets" },
    9: { p: "What are four parts of the lymph system?", a: "lymph vessels, lymph nodes, spleen, thymus" },
    10: { p: "What are some parts of the respiratory system?", a: "nose, pharynx, larynx, trachea, bronchi, bronchioles, alveoli, lungs" },
    11: { p: "What is the endocrine system?", a: "The endocrine system consists of glands and organs that use hormones to send messages through the bloodstream to the rest of the body." },
    12: { p: "What are the major purposes of blood?", a: "transportation, communication, regulation, protection" },
    13: { p: "What is the atomic number?", a: "The atomic number is the number of protons in the nucleus of an atom, which is also the number of electrons in a neutral atom." },
    14: { p: "What is an element?", a: "An element is a basic chemical substance defined by its atomic number and atomic mass." },
    15: { p: "What are some parts of an atom?", a: "nucleus, protons, electrons, quarks, leptons, neutrons" },
    16: { p: "What are the first four elements in the periodic table?", a: "1 Hydrogen (H) 1, 2 Helium (He) 4, 3 Lithium (Li) 7, 4 Beryllium (Be) 9" },
    17: { p: "What are the second four elements in the periodic table?", a: "5 Boron (B) 11, 6 Carbon (C) 12, 7 Nitrogen (N) 14, 8 Oxygen (O) 16" },
    18: { p: "What are the third four elements in the periodic table?", a: "9 Fluorine (F) 19, 10 Neon (Ne) 20, 11 Sodium (Na) 23, 12 Magnesium (Mg) 24" },
    19: { p: "What is the difference between an acid and a base?", a: "An acid donates a hydrogen ion and a base accepts a hydrogen ion." },
    20: { p: "What is natural selection?", a: "Natural selection is the idea that the fittest survive and pass along their traits to their offspring." },
    21: { p: "What does the theory of evolution rely on?", a: "The theory of evolution relies on the belief that life began as a chance combination of non-living things." },
    22: { p: "What does the theory of intelligent design rely on?", a: "The theory of intelligent design relies on the belief that life began as a result of intention and purpose." },
    23: { p: "What are some ways earth's history is preserved?", a: "rocks, fossils, ice, tar, amber" },
    24: { p: "What do the heavens declare?", a: "The heavens declare the glory of God; the skies proclaim the work of his hands. (Psalm 19:1)" }
  },

  "English": {
    1: { p: "An Infinitive", a: "An infinitive is 'to' plus a verb, used as a noun, adjective, or adverb." },
    2: { p: "A Present Participle", a: "A present participle is a verb plus '-ing,' used as an adjective or a verb." },
    3: { p: "A Past Participle", a: "A past participle is a verb plus '-ed,' used as an adjective or a verb." },
    4: { p: "Verb: Principal Parts", a: "infinitive, present, past, present participle, past participle" },
    5: { p: "To Be", a: "to be, am/are/is, was/were, being, been" },
    6: { p: "To Do", a: "to do, do/does, did, doing, done" },
    7: { p: "To Rise", a: "to rise, rise/rises, rose, rising, risen" },
    8: { p: "To Raise", a: "to raise, raise/raises, raised, raising, raised" },
    9: { p: "To Lay", a: "to lay, lay/lays, laid, laying, laid" },
    10: { p: "To Lie", a: "to lie, lie/lies, lay, lying, lain" },
    11: { p: "To Set", a: "to set, set/sets, set, setting, set" },
    12: { p: "To Sit", a: "to sit, sit/sits, sat, sitting, sat" },
    13: { p: "To Beat", a: "to beat, beat/beats, beat, beating, beaten" },
    14: { p: "To Break", a: "to break, break/breaks, broke, breaking, broken" },
    15: { p: "To Write", a: "to write, write/writes, wrote, writing, written" },
    16: { p: "To Go", a: "to go, go/goes, went, going, gone" },
    17: { p: "Sentence Parts: Subject", a: "The subject is that part of a sentence about which something is being said." },
    18: { p: "Sentence Parts: Predicate", a: "The predicate is that part of a sentence that says something about the subject." },
    19: { p: "Sentence Parts: Clause", a: "A clause is a group of words that contains both a subject and a verb." },
    20: { p: "Independent Clause", a: "An independent clause expresses a complete thought like a sentence." },
    21: { p: "Subordinate Clause", a: "A subordinate clause (dependent) does not express a complete thought and cannot stand alone." },
    22: { p: "Sentence Parts: Phrase", a: "A phrase is a group of words that does not contain both a subject and a verb." },
    23: { p: "Four Sentence Structures", a: "simple, compound, complex, compound-complex" },
    24: { p: "Seven Sentence Patterns", a: "S-V, S-V-DO, S-V-PN, S-V-PA, S-V-IO-DO, S-V-DO-OCN, S-V-DO-OCA" }
  },

  "History": {
    1: { p: "Tell me about Columbus.", a: "In 1492, Columbus made the first of four trips to the Caribbean on three Spanish ships named the Niña, the Pinta, and the Santa María." },
    2: { p: "Tell me about the Pilgrims.", a: "In 1620, the Pilgrims sailed from Plymouth, England and signed the Mayflower Compact before founding Plymouth Colony in North America." },
    3: { p: "Tell me about the Boston Tea Party.", a: "In 1773, colonists disguised as Mohawks dumped tea from the British East India Company into the Boston Harbor." },
    4: { p: "Tell me about the Declaration of Independence.", a: "In 1776, the Continental Congress published the Declaration of Independence in Philadelphia, announcing the colonists' intent to separate from England." },
    5: { p: "Tell me about George Washington.", a: "In 1789, in New York, George Washington was granted the full powers and responsibilities of the presidency by the U.S. Constitution." },
    6: { p: "Tell me about the Louisiana Purchase.", a: "In 1803, the purchase of Louisiana from France prompted westward exploration by pioneers such as Lewis and Clark and Congressman Davy Crockett." },
    7: { p: "Tell me about the Monroe Doctrine.", a: "After victory in the War of 1812, the United States wrote the Monroe Doctrine, which warned Europeans not to attempt to colonize the Americas." },
    8: { p: "Tell me about the Missouri Compromise.", a: "In 1820, Henry Clay worked out the Missouri Compromise, allowing Missouri to enter the Union as a slave state and Maine as a free state." },
    9: { p: "Tell me about Manifest Destiny.", a: "President Polk believed that the Mexican War and the Gadsden Purchase in the mid-1800s affirmed America's manifest destiny to spread across the continent." },
    10: { p: "Tell me about the secession of the Southern states.", a: "The Compromise of 1850, the Fugitive Slave Act, and the Dred Scott decision preceded the secession of the Southern states." },
    11: { p: "Tell me about the Civil War.", a: "In 1861, the Civil War began when President Abraham Lincoln went to war with the Southern states that had seceded from the Union." },
    12: { p: "Tell me about General Robert E. Lee.", a: "In 1865, General Robert E. Lee surrendered to General Ulysses S. Grant at Appomattox Court House in Virginia." },
    13: { p: "Tell me about the Fourteenth Amendment.", a: "In 1868, the Fourteenth Amendment made all former slaves U.S. citizens and paved the way for the Civil Rights Movement." },
    14: { p: "Tell me about tycoons.", a: "During the late 1800s, tycoons like Vanderbilt, Rockefeller, Carnegie, and Swift fueled the nation's Industrial Age by developing American resources." },
    15: { p: "Tell me about immigrants coming to America.", a: "From 1820 to 1930, more than 37 million immigrants came to America, seeking freedom and the opportunity to increase their personal wealth." },
    16: { p: "Tell me about the U.S. and World War I.", a: "In 1917, President Wilson asked Congress to enter World War I against the Central Powers two years after German U-boats sank the Lusitania." },
    17: { p: "Tell me about the Nineteenth Amendment.", a: "Elizabeth Cady Stanton and Susan B. Anthony led the women's suffrage movement, resulting in the Nineteenth Amendment in 1920 that granted women the right to vote." },
    18: { p: "Tell me about Pearl Harbor.", a: "On December 7, 1941, the Japanese bombed Pearl Harbor, Hawaii, causing the United States to join the Allies in World War II." },
    19: { p: "Tell me about NATO.", a: "In 1949, the United States and its allies formed NATO to resist the spread of Soviet communism." },
    20: { p: "Tell me about Brown v. Board of Education.", a: "In 1954, the U.S. Supreme Court ruled that the segregation of public schools by race is unconstitutional." },
    21: { p: "Tell me about U.S. astronauts.", a: "In 1969, U.S. astronauts Neil Armstrong and Edwin Aldrin were the first men to walk on the moon." },
    22: { p: "Tell me about September 11, 2001.", a: "Terrorists hijacked four airplanes, flying them into the World Trade Center, the Pentagon, and a Pennsylvania field." },
    23: { p: "Tell me the Preamble to the U.S. Constitution.", a: "We the People of the United States, in order to form a more perfect Union, establish Justice, insure domestic Tranquility..." },
    24: { p: "Tell me the Bill of Rights.", a: "1. Freedoms, 2. Own guns, 3. Quartering soldiers, 4. Warrants, 5. Cannot testify against self, 6. Right to speedy trial, 7. Right to a jury, 8. Cruel/unusual punishment, 9. People's rights, 10. States' rights" }
  },

  "Geography": {
    1: { p: "States and Capitals", a: "Augusta, ME; Concord, NH; Boston, MA; Providence, RI; Hartford, CT" },
    2: { p: "States and Capitals", a: "Montpelier, VT; Albany, NY; Trenton, NJ; Harrisburg, PA; Dover, DE" },
    3: { p: "States and Capitals", a: "Annapolis, MD; Richmond, VA; Charleston, WV; Raleigh, NC; Columbia, SC" },
    4: { p: "States and Capitals", a: "Washington, DC; Atlanta, GA; Tallahassee, FL; Montgomery, AL; Jackson, MS" },
    5: { p: "States and Capitals", a: "Lansing, MI; Columbus, OH; Indianapolis, IN; Frankfort, KY; Nashville, TN" },
    6: { p: "States and Capitals", a: "Madison, WI; Springfield, IL; Des Moines, IA; Jefferson City, MO; Little Rock, AR" },
    7: { p: "States and Capitals", a: "St. Paul, MN; Bismarck, ND; Pierre, SD; Cheyenne, WY; Lincoln, NE" },
    8: { p: "States and Capitals", a: "Topeka, KS; Oklahoma City, OK; Austin, TX; Denver, CO; Santa Fe, NM" },
    9: { p: "States and Capitals", a: "Salt Lake City, UT; Phoenix, AZ; Carson City, NV; Sacramento, CA; Honolulu, HI" },
    10: { p: "States and Capitals", a: "Helena, MT; Boise, ID; Olympia, WA; Salem, OR; Juneau, AK" },
    11: { p: "Northern Appalachian Mountains", a: "White Mountains, Green Mountains, Adirondack Mountains, Allegheny Mountains" },
    12: { p: "Southern Appalachian Mountains", a: "The Great Valley, Blue Ridge Mountains, Great Smoky Mountains, Cumberland Mountains, Mt. Mitchell" },
    13: { p: "Western Mountains", a: "Rocky Mountains, Pikes Peak, Mt. Elbert, Sierra Nevadas, Mt. Whitney" },
    14: { p: "Mountains", a: "Cascade Mountains, Mt. Rainier, Mt. St. Helens, Denali" },
    15: { p: "Great Lakes", a: "Huron, Ontario, Michigan, Erie, Superior" },
    16: { p: "Bays", a: "Chesapeake Bay, San Francisco Bay, Puget Sound, Hudson Bay, Pamlico Sound" },
    17: { p: "Rivers (East)", a: "St. Lawrence River, Ohio River, Mississippi River, Missouri River, Arkansas River" },
    18: { p: "Rivers (West)", a: "Colorado River, Red River, Rio Grande River, Columbia River, Great Salt Lake" },
    19: { p: "Trails", a: "Cumberland Road, Santa Fe Trail, Mormon Trail, Gila Trail, Old Spanish Trail, California Trail, Oregon Trail" },
    20: { p: "Canals", a: "Erie Canal, Pennsylvania Canal, Chesapeake and Ohio Canal, Ohio and Erie Canal, Miami and Erie Canal" },
    21: { p: "Native American Regions", a: "Eastern Woodlands, Plains, Plateau, Northwest Coast, California, Great Basin, Southwest" },
    22: { p: "Deserts", a: "Colorado Desert, Mojave Desert, Sonoran Desert, Painted Desert, Great Salt Lake Desert" },
    23: { p: "Prominent Features", a: "Grand Canyon, Black Hills, Ozark Highlands, Okefenokee Swamp, Olympic Rain Forests, Niagara Falls" },
    24: { p: "More Prominent Features", a: "Mississippi River Delta, Mammoth Cave, San Andreas Fault, Gulf of Mexico, Death Valley" }
  },

 "Bible": {
    1: { p: "What are the two major themes of the Bible?", a: "Who God is and His covenant with man" },
    2: { p: "What are the two major divisions of the Bible?", a: "Old Testament, New Testament" },
    3: { p: "What are the seven subdivisions of the Bible?", a: "Law, History, Poetry, Prophets, Gospels, Letters, Prophecy" },
    4: { p: "List the 66 books of the Bible in order: Old Testament (Part 1)", a: "Genesis, Exodus, Leviticus, Numbers, Deuteronomy, Joshua, Judges, Ruth" },
    5: { p: "List the 66 books of the Bible in order: Old Testament (Part 2)", a: "1 Samuel, 2 Samuel, 1 Kings, 2 Kings, 1 Chronicles, 2 Chronicles, Ezra, Nehemiah, Esther, Job" },
    6: { p: "List the 66 books of the Bible in order: Old Testament (Part 3)", a: "Psalms, Proverbs, Ecclesiastes, Song of Songs, Isaiah, Jeremiah" },
    7: { p: "List the 66 books of the Bible in order: Old Testament (Part 4)", a: "Lamentations, Ezekiel, Daniel, Hosea, Joel, Amos, Obadiah, Jonah" },
    8: { p: "List the 66 books of the Bible in order: Old Testament (Part 5)", a: "Micah, Nahum, Habakkuk, Zephaniah, Haggai, Zechariah, Malachi" },
    9: { p: "List the 66 books of the Bible in order: New Testament (Part 1)", a: "Matthew, Mark, Luke, John, Acts" },
    10: { p: "List the 66 books of the Bible in order: New Testament (Part 2)", a: "Romans, 1 Corinthians, 2 Corinthians, Galatians, Ephesians, Philippians, Colossians" },
    11: { p: "List the 66 books of the Bible in order: New Testament (Part 3)", a: "1 Thessalonians, 2 Thessalonians, 1 Timothy, 2 Timothy, Titus, Philemon, Hebrews" },
    12: { p: "List the 66 books of the Bible in order: New Testament (Part 4)", a: "James, 1 Peter, 2 Peter, 1 John, 2 John, 3 John, Jude, Revelation" },
    13: { p: "How is Jesus portrayed in each Gospel?", a: "Matthew: as King; Mark: as Servant; Luke: as Man; John: as God" },
    14: { p: "What are the names of Jesus' original twelve disciples? (Part 1)", a: "Peter, John, James (the brother of John), Andrew, Philip" },
    15: { p: "What are the names of Jesus' original twelve disciples? (Part 2)", a: "Thomas, Bartholomew, Matthew, James (the son of Alphaeus), Simon the Zealot, Thaddaeus, Judas Iscariot" },
    16: { p: "Who was Judas Iscariot?", a: "The disciple who betrayed Jesus and delivered Him over to the Jewish chief priests" },
    17: { p: "What is God's new covenant with man?", a: "Jesus, the perfect sacrifice for sin; Eternal life to those who believe; The Holy Spirit lives within believers" },
    18: { p: "What does the book of Acts record?", a: "The ascension of Christ; Pentecost; Powerful acts of God through the Church" },
    19: { p: "Who was Saul of Tarsus?", a: "A Jewish leader (later known as Paul) who at first persecuted Christians but then received Jesus, became a devoted follower of Christ, and wrote most of the New Testament" },
    20: { p: "Peter and Paul took the Gospel to which groups of people?", a: "Peter: to the Jews; Paul: to the Gentiles" },
    21: { p: "How is Satan described in 1 Peter?", a: "A roaring lion, prowling about and seeking whom he may devour" },
    22: { p: "What book of the New Testament is typically considered a prophecy of the end times?", a: "Revelation, written by the apostle John" },
    23: { p: "The rebuilding of the third Jewish temple is usually associated with what important event?", a: "Jesus' return to the earth" },
    24: { p: "What is the main original language of the New Testament?", a: "Koine Greek" }
  },

  "Timeline": {
    1: { p: "Age of Ancient Empires - Minoans and Mycenaeans", a: "AGE OF ANCIENT EMPIRES (Creation to circa 450 AD), Creation and the Fall, The Flood and the Tower of Babel, Mesopotamia and Sumer, Egyptians, (3000 BC) Indus River Valley Civilization, Minoans and Mycenaeans" },
    2: { p: "Seven Wonders of the Ancient World - China's Shang Dynasty", a: "Seven Wonders of the Ancient World, Patriarchs of Israel, (2000 BC) Hittites and Canaanites, Kush, Assyrians, Babylonians, China's Shang Dynasty" },
    3: { p: "Hinduism in India - Israel's United Kingdom", a: "Hinduism in India, Phoenicians and the Alphabet, Olmecs of Mesoamerica, Israelite Exodus and Desert Wandering, Israelite Conquest and Judges, Greek Dark Ages, Israel's United Kingdom" },
    4: { p: "Early Native Americans - Lao-Tzu, Confucius, Buddha", a: "(1000 BC) Early Native Americans, Israel Divides into Two Kingdoms, Homer and Hesiod, Rome Founded by Romulus and Remus, Israel Falls to Assyria, Assyria Falls to Babylon, Lao-Tzu, Confucius, Buddha" },
    5: { p: "Judah Falls to Babylon - Persia Falls to Alexander the Great", a: "Judah Falls to Babylon, Temple Destroyed, Babylon Falls to Persia, Jews Return and Rebuild the Temple, Roman Republic, Golden Age of Greece, Peloponnesian Wars, Persia Falls to Alexander the Great" },
    6: { p: "India's Mauryan Empire - John the Baptist", a: "India's Mauryan Empire, Mayans of Mesoamerica, Punic Wars, Rome Conquers Greece, Roman Dictator Julius Caesar, Caesar Augustus and the Pax Romana, John the Baptist" },
    7: { p: "Jesus the Messiah - India's Gupta Dynasty", a: "Jesus the Messiah, (Year 1 AD) Pentecost and the Early Church, Persecution Spreads the Gospel, Herod's Temple Destroyed by Titus, Diocletian Divides the Roman Empire, Constantine Legalizes Christianity, India's Gupta Dynasty" },
    8: { p: "Council of Nicea - Western Roman Empire Falls to Barbarians", a: "Council of Nicea, Augustine of Hippo, Jerome Completes the Vulgate, Visigoths Sack Rome, THE MIDDLE AGES (circa 450-1500) Council of Chalcedon, Western Roman Empire Falls to Barbarians" },
    9: { p: "Byzantine Emperor Justinian - Vikings Raid and Trade", a: "(500 AD) Byzantine Emperor Justinian, Benedict and Monasticism, Muhammad Founds Islam, Zanj and Early Ghana, Franks Defeat Muslims at the Battle of Tours, Golden Age of Islam, Vikings Raid and Trade" },
    10: { p: "Japan's Heian Period - East-West Schism of the Church", a: "Japan's Heian Period, Charlemagne Crowned Emperor of Europe, Alfred the Great, Erik the Red and Leif Eriksson, Vladimir I of Kiev, Byzantine Emperor Basil II, (1000 AD) East-West Schism of the Church" },
    11: { p: "Norman Conquest and Feudalism in Europe - Incas of South America", a: "Norman Conquest and Feudalism in Europe, The Crusades, Zimbabwe and Early Mali in Africa, Aztecs of Mesoamerica, Francis of Assisi and Thomas Aquinas, Japan's Shoguns, Incas of South America" },
    12: { p: "Genghis Khan Rules the Mongols - China's Ming Dynasty", a: "Genghis Khan Rules the Mongols, England's Magna Carta, Ottoman Empire, Marco Polo's Journey to China, The Hundred Years' War and Black Death, The Renaissance, China's Ming Dynasty" },
    13: { p: "Age of Exploration - The Spanish Inquisition", a: "AGE OF EXPLORATION (c. 1400-1600), Prince Henry Founds School of Navigation, Slave Trade in Africa, Gutenberg's Printing Press, Songhai in Africa, Czar Ivan the Great of Russia, The Spanish Inquisition" },
    14: { p: "Columbus Sails to the Caribbean - Baroque Period of the Arts", a: "Columbus Sails to the Caribbean, (1500 AD) AGE OF ABSOLUTE MONARCHS (c. 1500-1800), Protestant Reformation, Spanish Conquistadors in the Americas, Calvin's Institutes of the Christian Religion, Council of Trent, Baroque Period of the Arts" },
    15: { p: "Japan's Isolation - The Seven Years' War", a: "Japan's Isolation, Jamestown and Plymouth Colony Founded, AGE OF ENLIGHTENMENT (c. 1650-1800), Hudson's Bay Company, First Great Awakening, Classical Period of the Arts, The Seven Years' War" },
    16: { p: "Age of Industry - Louisiana Purchase and Lewis and Clark Expidition", a: "AGE OF INDUSTRY (c. 1760-1969), James Cook Sails to Australia, American Revolution and General George Washington, Madison's Constitution and the Bill of Rights, French Revolution, Second Great Awakening, Louisiana Purchase and Lewis and Clark Expedition" },
    17: { p: "Napoleon to Romantic Period of the Arts", a: "Napoleon Crowned Emperor of France, Liberation of South America, The War of 1812, The Missouri Compromise, Immigrants Flock to America, The Monroe Doctrine, Romantic Period of the Arts" },
    18: { p: "Cherokee Trail of Tears to Darwin Publishes The Origin of Species", a: "Cherokee Trail of Tears, U.S. Westward Expansion, Marx Publishes The Communist Manifesto, The Compromise of 1850 and Dred Scott Decision, U.S. Restores Trade with Japan, British Queen Victoria's Rule Over India, Darwin Publishes The Origin of Species" },
    19: { p: "Lincoln's War Between the States to The Progressive Era", a: "Lincoln's War Between the States, Reconstruction of the Southen States, Dominion of Canada, Otto von Bismarck Unifies Germany, Boer Wars in Africa, The Spanish-American War, The Progressive Era" },
    20: { p: "Australia Becomes a Commonwealth to The Great Depression and the New Deal", a: "Australia Becomes a Commonwealth, Mexican Revolution, World War I and President Wilson, Lenin and the Bolshevik Revolution in Russia, U.S. Evangelist Billy Graham, Modern Period of the Arts, The Great Depression and the New Deal" },
    21: { p: "World War II to Mao and Communist Victory in China", a: "World War II and President Franklin D. Roosevelt, Stalin of the USSR and the Katyn Massacre, The United Nations Formed, The Cold War, Gandhi and India's Independence, Jewish State Established, Mao and Communist Victory in China" },
    22: { p: "North Atlantic Treaty Organization to U.S. Astronauts Walk on the Moon", a: "North Atlantic Treaty Organization, The Korean War, Martin Luther King, Jr. and the Civil Rights Movement, Jim and Elisabeth Elliot - Missionaries to Ecuador, The Antarctic Treaty, The Vietnam War, U.S. Astronauts Walk on the Moon, " },
    23: { p: "Age of Information and Globalization to Rising Tide of Freedom", a: "AGE OF INFORMATION AND GLOBALIZATION (c. 1970-present), Watergate and President Nixon Resigns, Fall of Communism in Eastern Europe, European Union Formed, Apartheid Abolished in South Africa, (2000 AD) September 11, 2001, Rising Tide of Freedom" },
    24: { p: "Canadian Prime Ministers", a: "Macdonald, Mackenzie, Macdonald, Abbott, Thompson, Bowell, Tupper, Laurier, Borden, Meighen, King, Meighen, King, Bennett, King, St. Laurent, Diefenbaker, Pearson, Trudeau, Clark, Trudeau, Turner, Mulroney, Campbell, Chrétien, Martin, Harper, Trudeau, Carney" }
  }
};